/**
  * Copyright (C) 2007-8, Paul Ponec, contact: http://ponec.net/
  *
  * This program is free software; you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation version 2 of the License.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * You may obtain a copy of the License at
  * http://www.gnu.org/licenses/gpl-2.0.txt
  */


package net.ponec.jworksheet.gui;

import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import net.ponec.jworksheet.core.ApplContext;
import net.ponec.jworksheet.core.ApplTools;

/**
 * A General Top Dialog.
 * @author  Pavel Ponec
 */
public class TopDialog extends javax.swing.JDialog {
    
    protected ApplContext applContext;
    
    /** Creates new form TopDialog */
    public TopDialog(ApplContext aContext) {
        super(aContext.getTopFrame(), true);
        applContext = aContext;
        setName("");
        initComponents();
        
        ApplTools.registerEscapeAction(getRootPane(), new AbstractAction("escape") {
            public void actionPerformed(ActionEvent e) { escapeAction(e); }
        });        
        
    }
    
    /** Initialization by a child. */
    protected void init() {
        //pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-getWidth())/2, (screenSize.height-getHeight())/2, getWidth(), getHeight());
    }
    
    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            init();
        }
        super.setVisible(visible);
    }

    public void escapeAction(ActionEvent e) {
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
