/**
 * Copyright (C) 2007-8, Paul Ponec, contact: http://ponec.net/
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation version 2 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You may obtain a copy of the License at
 * http://www.gnu.org/licenses/gpl-2.0.txt
 */

package net.ponec.jworksheet.core;

/**
 * In the debug mode it display to user a language property parameters
 * from top hierarchy komponent to down recursively.
 *
 * @author  Pavel Ponec
 * @version 1.1
 */
public class LanguageManagerDialog extends javax.swing.JDialog {
    
    // ---------- Constructors -------------------
    
    /** Creates new LanguageManagerDialogDialog class.
     * @param basicContainer Parameter is default Root. It is used alse for PROPERTY file name.
     */
    public LanguageManagerDialog
    ( java.awt.Container basicContainer
    , String properties
    , String warnings
    ) {
        super((java.awt.Frame) basicContainer, true);
        initComponents();
        tProperties.setText(properties);
        tWarnings  .setText(warnings);
        
        setVisible(true);
    }
    
    /**  For GUI test only. Creates new form LangKeyTool for an Frame.
     */
    private LanguageManagerDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        setVisible(true);
    }
    
    // ----------- Methods --------------------
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        bClose = new javax.swing.JButton();
        bConvert = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        spProperties = new javax.swing.JScrollPane();
        tProperties = new javax.swing.JTextArea();
        spWarnings = new javax.swing.JScrollPane();
        tWarnings = new javax.swing.JTextArea();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setTitle("Language Manager");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        bClose.setMnemonic('C');
        bClose.setText("Close");
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 2);
        getContentPane().add(bClose, gridBagConstraints);

        bConvert.setText("To ASCII");
        bConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConvertActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 5, 0);
        getContentPane().add(bConvert, gridBagConstraints);

        tProperties.setText("This is only test");
        spProperties.setViewportView(tProperties);

        jTabbedPane1.addTab("Properties", null, spProperties, "");

        spWarnings.setViewportView(tWarnings);

        jTabbedPane1.addTab("Warnings", null, spWarnings, "");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
    }//GEN-END:initComponents
    
    private void bConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConvertActionPerformed
        String s       = tProperties.getText();
        String o       = null;
        StringBuffer sb = new StringBuffer(s.length()*2);
        int i, j;
        
        for (i=0 ; i<s.length(); i++) {
            if (s.charAt(i)<'\u0080') sb.append(s.charAt(i));
            else {
                sb.append("\\u");
                o = Integer.toHexString((int)s.charAt(i));
                for (j=4-o.length(); j>0; j--) sb.append("0");
                sb.append(o);
            }
        }
        tProperties.setText(sb.toString());
    }//GEN-LAST:event_bConvertActionPerformed
    
    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        closeDialog(null);
    }//GEN-LAST:event_bCloseActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private javax.swing.JButton bConvert;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane spProperties;
    private javax.swing.JScrollPane spWarnings;
    private javax.swing.JTextArea tProperties;
    private javax.swing.JTextArea tWarnings;
    // End of variables declaration//GEN-END:variables
    
    
    // ======== THE TESTING ONLY ================
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new LanguageManagerDialog((java.awt.Frame) null);
        java.lang.System.err.println("THE END ! " + LanguageManagerDialog.class.getName());
        System.exit(0);
    }
    
    
    
}
